import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [{type: 'autogenerated', dirName: 'learn'}],
  buildSidebar: [{type: 'autogenerated', dirName: 'build'}],
  operatorsSidebar: [{type: 'autogenerated', dirName: 'operators'}],
  stakersSidebar: [{type: 'autogenerated', dirName: 'stakers'}],
  basedApplicationsSidebar: [{type: 'autogenerated', dirName: 'based-applications'}],

  // But you can create a sidebar manually
  /*
  learnSideBar: [
    {
      type: 'category',
      label: 'Learn',
      items: ['learn/'],
    },
  ],
   */

  docs: [
    {
      type: 'category',
      label: 'Learn',
      items: [
        'learn/glossary',
        // Other learn section files will be added here
      ],
    },
    // Other existing categories...
  ],
};

export default sidebars;
