{
 "title": "SSV Operational",
 "time": { "from": "2024-12-23T09:16:29.165Z", "to": "2024-12-23T09:31:43.372Z" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(otel_scope_info{otel_scope_name=~\"github.com/ssvlabs/.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "Validator count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_validator_validators_per_status{pod=~\"$pod\", ssv_validator_status!=\"slashed\"}) by (ssv_validator_status)",
       "legendFormat": "{{ssv_validator_status}}"
      },
      {
       "expr": "sum(ssv_validator_validators_per_status{pod=~\"$pod\", ssv_validator_status=\"slashed\"}) by (ssv_validator_status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Syncer Last Block",
     "type": "stat",
     "description": "This is responsible for syncing SSV network smart contract events.",
     "gridPos": { "h": 4, "w": 7, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_event_syncer_handler_last_processed_block{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execution Layer Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "ssv_el_sync_status{pod=~\"$pod\", ssv_el_status=\"ready\"} != 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "ssv_el_sync_status{pod=~\"$pod\", ssv_el_status!=\"ready\"} != 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execution Layer Client",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "expr": "ssv_el_sync_status{pod=~\"$pod\", ssv_el_status=\"ready\"} != 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "ssv_el_sync_status{pod=~\"$pod\", ssv_el_status!=\"ready\"} != 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Layer Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "ssv_cl_sync_status{pod=~\"$pod\", ssv_cl_sync_status=\"synced\"} != 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "ssv_cl_sync_status{pod=~\"$pod\", ssv_cl_sync_status!=\"synced\"} != 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Layer Client",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "ssv_cl_sync_status{pod=~\"$pod\", ssv_cl_sync_status=\"synced\"} != 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "ssv_cl_sync_status{pod=~\"$pod\", ssv_cl_sync_status!=\"synced\"} != 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Peers ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssv_p2p_peers_connected{pod=~\"$pod\"}",
       "legendFormat": "Peers"
      }
     ]
    },
    {
     "title": "Connections ",
     "type": "stat",
     "description": "If one of these two is very low it might signal that you have issues reaching out other peers, or that other peers can't connect to you.",
     "gridPos": { "h": 3, "w": 7, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_p2p_connections_active{pod=~\"$pod\"}) by (ssv_p2p_connection_direction)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consensus Layer Request Duration",
     "type": "heatmap",
     "description": "This is the latency to the Consensus Layer client for all calls. If you want a breakdown of which calls take longer or percentiles, scroll to the `Ethereum Clients` section.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum(rate(ssv_cl_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Peer Versions",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ssv_p2p_peers_per_version{pod=~\"$pod\"}) by (ssv_node_version)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connected peers per topic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(ssv_p2p_peers_per_topic{pod=~\"$pod\"}) by (ssv_p2p_topic_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Submitted Attestations vs Expected",
     "type": "timeseries",
     "description": "All validators have to attest once per epoch. We can estimate performance by looking at `active validators` / `submitted attestations by the SSV node`. Submitted attestations have a delay of 1 epoch so if the node was restarted recently it will not have enough information about the first epoch since restart.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(ssv_validator_submissions{pod=~\"$pod\", ssv_beacon_role=\"ATTESTER\"}) / sum(ssv_validator_validators_per_status{pod=~\"$pod\", ssv_validator_status=\"participating\"})",
       "legendFormat": "Submitted percentage"
      }
     ]
    }
   ]
  },
  { "title": "P2P Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Accepted peers per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_discovery_peers_accepted_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Skipped peers per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_discovery_peers_skipped_total{pod=~\"$pod\"}[$__rate_interval])) by (pod, ssv_p2p_discovery_skip_reason)",
     "legendFormat": "{{pod}} - {{ssv_p2p_discovery_skip_reason}}"
    }
   ]
  },
  {
   "title": "Discovered peers per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_discovery_peers_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "P2P Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Peers connected to per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(ssv_p2p_connections_connected_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers disconnected from per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(ssv_p2p_connections_disconnected_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers filtered per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(ssv_p2p_connections_filtered_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected peer count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(ssv_p2p_peers_connected{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "Peers connected {{pod}}"
    },
    {
     "expr": "sum(ssv_p2p_connections_active{pod=~\"$pod\"}) by (ssv_p2p_connection_direction, pod)",
     "legendFormat": "{{ssv_p2p_connection_direction}} peers {{pod}}"
    }
   ]
  },
  {
   "title": "Connected peers per topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(ssv_p2p_peers_per_topic{pod=~\"$pod\"}) by (ssv_p2p_topic_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected peers per version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(ssv_p2p_peers_per_version{pod=~\"$pod\"}) by (ssv_node_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "P2P Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Messages per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_messages_in_total{pod=~\"$pod\"}[$__rate_interval])) by (pod) * 60",
     "legendFormat": "in {{pod}}"
    },
    {
     "expr": "-(sum(rate(ssv_p2p_messages_out_total{pod=~\"$pod\"}[$__rate_interval])) by (pod) * 60)",
     "legendFormat": "out {{pod}}"
    }
   ]
  },
  {
   "title": "Stream requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_stream_requests_received_total{pod=~\"$pod\"}[$__rate_interval])) * 60",
     "legendFormat": "received"
    },
    {
     "expr": "-(sum(rate(ssv_p2p_stream_requests_sent_total{pod=~\"$pod\"}[$__rate_interval])) * 60)",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Stream responses per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_stream_responses_received_total{pod=~\"$pod\"}[$__rate_interval])) * 60",
     "legendFormat": "received"
    },
    {
     "expr": "-(sum(rate(ssv_p2p_stream_responses_sent_total{pod=~\"$pod\"}[$__rate_interval])) * 60)",
     "legendFormat": "sent"
    }
   ]
  },
  { "title": "P2P Message Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Message Validation Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_message_validations_accepted_total{pod=~\"$pod\"}[$__rate_interval])) * 60",
     "legendFormat": "Accepted messages"
    },
    {
     "expr": "sum(rate(ssv_p2p_message_validations_ignored_total{pod=~\"$pod\"}[$__rate_interval])) * 60",
     "legendFormat": "Ignored messages"
    },
    {
     "expr": "sum(rate(ssv_p2p_message_validations_rejected_total{pod=~\"$pod\"}[$__rate_interval])) * 60",
     "legendFormat": "Rejected messages"
    }
   ]
  },
  {
   "title": "Message Validation Rejected by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_message_validations_rejected_total{pod=~\"$pod\"}[$__rate_interval])) by (ssv_p2p_message_validation_discard_reason) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Validation Ignored by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_message_validations_ignored_total{pod=~\"$pod\"}[$__rate_interval])) by (ssv_p2p_message_validation_discard_reason) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Validation Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(rate(ssv_p2p_message_validations_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Duty Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Slot Delay Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(ssv_duty_scheduler_slot_ticker_delay_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Duties Scheduled per Role",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "duties/min" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_duty_scheduler_executions_total{pod=~\"$pod\"}[$__rate_interval])) by (ssv_runner_role) * 60",
     "legendFormat": "{{ssv_beacon_role}}"
    }
   ]
  },
  { "title": "Event Syncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Last processed block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_event_syncer_handler_last_processed_block{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events successfully processed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 75 },
   "targets": [
    {
     "expr": "sum(rate(ssv_event_syncer_handler_events_processed_total{pod=~\"$pod\"}[$__rate_interval])) by (ssv_event_syncer_event_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event processing failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 75 },
   "targets": [
    {
     "expr": "sum(rate(ssv_event_syncer_handler_events_failed_total{pod=~\"$pod\"}[$__rate_interval])) by (ssv_event_syncer_event_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Runners", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Pre Consensus Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_pre_consensus_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_consensus_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Post Consensus Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_post_consensus_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duty full flow duration histogram ATTESTER role",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_duration_seconds_bucket{pod=~\"$pod\", ssv_beacon_role=\"ATTESTER\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duty full flow duration histogram AGGREGATOR role",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_duration_seconds_bucket{pod=~\"$pod\", ssv_beacon_role=\"AGGREGATOR\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duty full flow duration histogram SYNC COMMITTEE role",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_duration_seconds_bucket{pod=~\"$pod\", ssv_beacon_role=\"SYNC_COMMITTEE\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duty full flow duration histogram PROPOSER role",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_duty_duration_seconds_bucket{pod=~\"$pod\", ssv_beacon_role=\"PROPOSER\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of submissions per role",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum(ssv_validator_submissions{pod=~\"$pod\"}) by (ssv_beacon_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of failed submissions per role",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_submissions_failed_total{pod=~\"$pod\"}[$__rate_interval])) by (ssv_beacon_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Validator errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators removed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_validators_removed_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators per status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "sum(ssv_validator_validators_per_status{pod=~\"$pod\"}) by (ssv_validator_status, pod)",
     "legendFormat": "{{pod}} {{ssv_validator_status}}"
    }
   ]
  },
  { "title": "QBFT Consensus Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Validator Stage Duration per role",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_stage_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (ssv_runner_role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Stage Duration Per Stage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_stage_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (ssv_validator_stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Stage Duration per round",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ssv_validator_stage_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (ssv_validator_duty_round)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ethereum Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Execution Layer Syncing Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_el_sync_status{pod=~\"$pod\"} != 0) by (pod, ssv_el_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Layer Sync Distance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_el_sync_distance{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Layer Last Processed Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_el_sync_last_processed_block{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Client Latency (Sync Progress)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "sum(rate(ssv_el_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Layer Syncing Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 145 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_cl_sync_status{pod=~\"$pod\"} != 0) by (pod, ssv_cl_sync_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Layer Sync Distance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssv_cl_sync_distance{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Consensus Layer Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "sum(rate(ssv_cl_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Layer Successful Request Duration Per Method",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.90, sum(rate(ssv_cl_request_duration_seconds_bucket{pod=~\"$pod\", http_response_error_status_code=\"\"}[$__rate_interval])) by (http_route_name, le, http_request_method))",
     "legendFormat": ".90-{{http_request_method}}-{{http_route_name}}"
    },
    {
     "expr": "histogram_quantile(.50, sum(rate(ssv_cl_request_duration_seconds_bucket{pod=~\"$pod\", http_response_error_status_code=\"\"}[$__rate_interval])) by (http_route_name, le, http_request_method))",
     "legendFormat": ".50-{{http_request_method}}-{{http_route_name}}"
    }
   ]
  },
  {
   "title": "Consensus Layer Failed Request Count Per Method",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ssv_cl_request_duration_seconds_count{pod=~\"$pod\", http_response_error_status_code!=\"\"}) by (http_response_error_status_code, http_request_method, http_route_name, pod)",
     "legendFormat": "{{http_response_error_status_code}}-{{http_request_method}}-{{http_route_name}} {{pod}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 },
   "collapsed": true
  },
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 },
   "collapsed": true
  },
  {
   "title": "SSV API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 },
   "collapsed": true
  },
  {
   "title": "Beacon Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 },
   "collapsed": true
  },
  {
   "title": "Miscellaneous",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 },
   "collapsed": true
  }
 ]
}